import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by `pnpm cf-typegen`; not meant to be linted.
    "cloudflare-env.d.ts",
    // Wrangler build/dev artifacts.
    ".wrangler/**",
    // OpenNext build output (bundled/minified assets, not source).
    ".open-next/**",
    // Isolated remote dev output (generated by KLIPCODE_DIST_DIR).
    ".next-remote/**",
    // Auto-generated by `npx convex dev`; not meant to be linted.
    "convex/_generated/**",
  ]),
]);

export default eslintConfig;
